[package]
name = "vo-frontend"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dioxus = { workspace = true }
serde = { workspace = true }
serde_json.workspace = true
ulid.workspace = true
uuid.workspace = true
vo-types = { path = "../vo-types" }

bytes = { workspace = true }
chrono = { workspace = true }
itertools = { workspace = true }

wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
web-sys = { version = "0.3", optional = true, features = ["Window"] }
gloo-timers = { version = "0.3", optional = true }

[features]
default = []
wasm = ["wasm-bindgen", "wasm-bindgen-futures", "web-sys", "gloo-timers"]

[lints]
workspace = true
