[package]
name = "vo-sdk-macros"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
proptest = { workspace = true }
trybuild = "1.0"
tokio = { workspace = true }
