//! BDD Behavioral Contract Verification for vo-actor
//!
//! This module verifies behavioral contracts via Given/When/Then tests
//! exercising only the public API. Three lenses are applied:
//! 1. Liar Check — does implementation match documented claims?
//! 2. Breakage Check — what happens when conditions degrade?
//! 3. Completeness Check — is every public item exercised?
//!
//! Generated by bdd-enforcer for ve-be5o8.

use std::time::Duration;
use vo_actor::*;
use vo_actor::lifecycle::*;
use vo_actor::signal_buffer::*;
use vo_actor::instance_registry::*;
use vo_actor::spawn_supervisor::*;
use vo_actor::fairness::*;
use vo_actor::signal_messages::{
    self, AcceptResumeError, BinaryHash, CancelError, CancelRequested, ContinueAsNewError,
    InstanceResumed, LifecycleState, NodeName, ResumeError, RolloverState, SecretId,
    SignalAccepted, SignalPayload, SignalStorageError, SignalWorkQueueError, TimestampMs,
    WaitKey, WorkflowCancelled, WorkflowContinued,
};
use vo_actor::message_router::*;
use vo_actor::semaphore::types::*;
use vo_actor::reanimator::types as reanimator_types;
use vo_actor::timers::*;
use vo_types::{InstanceId, TimestampMs as VoTimestampMs};

// Helper to create valid InstanceId
fn iid(s: &str) -> InstanceId {
    InstanceId::parse(s).unwrap()
}

fn default_iid() -> InstanceId {
    iid("01H5JYV4XHGSR2F8KZ9BWNRFMA")
}

// ============================================================================
// MODULE 1: ActorLifecycleState FSM (lifecycle.rs)
// ============================================================================

mod bdd_lifecycle_fsm {
    use super::*;

    // --- Claim: Pending → Running is the only happy-path start ---
    #[test]
    fn given_pending_when_start_then_running() {
        let next = compute_next_state(ActorLifecycleState::Pending, LifecycleTransition::Start);
        assert_eq!(next, Some(ActorLifecycleState::Running));
    }

    // --- Claim: Pending can fail directly ---
    #[test]
    fn given_pending_when_fail_then_failed() {
        let next = compute_next_state(ActorLifecycleState::Pending, LifecycleTransition::Fail);
        assert_eq!(next, Some(ActorLifecycleState::Failed));
    }

    // --- Claim: Running → Stopping on Stop ---
    #[test]
    fn given_running_when_stop_then_stopping() {
        let next = compute_next_state(ActorLifecycleState::Running, LifecycleTransition::Stop);
        assert_eq!(next, Some(ActorLifecycleState::Stopping));
    }

    // --- Claim: Running can fail directly ---
    #[test]
    fn given_running_when_fail_then_failed() {
        let next = compute_next_state(ActorLifecycleState::Running, LifecycleTransition::Fail);
        assert_eq!(next, Some(ActorLifecycleState::Failed));
    }

    // --- Claim: Stopping → Stopping on ChildStopped (waits for siblings) ---
    #[test]
    fn given_stopping_when_child_stopped_then_still_stopping() {
        let next = compute_next_state(
            ActorLifecycleState::Stopping,
            LifecycleTransition::ChildStopped,
        );
        assert_eq!(next, Some(ActorLifecycleState::Stopping));
    }

    // --- Claim: Stopping → Stopped only when all children done ---
    #[test]
    fn given_stopping_when_all_children_stopped_then_stopped() {
        let next = compute_next_state(
            ActorLifecycleState::Stopping,
            LifecycleTransition::AllChildrenStopped,
        );
        assert_eq!(next, Some(ActorLifecycleState::Stopped));
    }

    // --- Liar Check: Terminal states reject ALL transitions ---
    #[test]
    fn given_terminal_when_any_transition_then_none() {
        let terminals = [ActorLifecycleState::Stopped, ActorLifecycleState::Failed];
        let transitions = [
            LifecycleTransition::Start,
            LifecycleTransition::Stop,
            LifecycleTransition::ChildStopped,
            LifecycleTransition::AllChildrenStopped,
            LifecycleTransition::Fail,
        ];
        for state in &terminals {
            for trans in &transitions {
                assert_eq!(
                    compute_next_state(*state, *trans),
                    None,
                    "Terminal {:?} must reject {:?}",
                    state,
                    trans
                );
            }
        }
    }

    // --- Claim: is_terminal is true only for Stopped and Failed ---
    #[test]
    fn is_terminal_classifies_correctly() {
        assert!(!ActorLifecycleState::Pending.is_terminal());
        assert!(!ActorLifecycleState::Running.is_terminal());
        assert!(!ActorLifecycleState::Stopping.is_terminal());
        assert!(ActorLifecycleState::Stopped.is_terminal());
        assert!(ActorLifecycleState::Failed.is_terminal());
    }

    // --- Claim: is_stopping is true for Stopping and Stopped ---
    #[test]
    fn is_stopping_classifies_correctly() {
        assert!(!ActorLifecycleState::Pending.is_stopping());
        assert!(!ActorLifecycleState::Running.is_stopping());
        assert!(ActorLifecycleState::Stopping.is_stopping());
        assert!(ActorLifecycleState::Stopped.is_stopping());
        assert!(!ActorLifecycleState::Failed.is_stopping());
    }

    // --- Claim: can_spawn_child only when Pending or Running ---
    #[test]
    fn can_spawn_child_classifies_correctly() {
        assert!(ActorLifecycleState::Pending.can_spawn_child());
        assert!(ActorLifecycleState::Running.can_spawn_child());
        assert!(!ActorLifecycleState::Stopping.can_spawn_child());
        assert!(!ActorLifecycleState::Stopped.can_spawn_child());
        assert!(!ActorLifecycleState::Failed.can_spawn_child());
    }

    // --- Claim: valid_transitions matches compute_next_state ---
    #[test]
    fn valid_transitions_matches_compute() {
        for state in [
            ActorLifecycleState::Pending,
            ActorLifecycleState::Running,
            ActorLifecycleState::Stopping,
            ActorLifecycleState::Stopped,
            ActorLifecycleState::Failed,
        ] {
            let valid = state.valid_transitions();
            for trans in valid {
                assert!(
                    is_valid_transition(state, trans),
                    "valid_transitions claims {:?} is valid from {:?} but is_valid_transition disagrees",
                    trans, state
                );
            }
        }
    }

    // --- Claim: Display outputs lowercase strings ---
    #[test]
    fn display_outputs_lowercase() {
        assert_eq!(format!("{}", ActorLifecycleState::Pending), "pending");
        assert_eq!(format!("{}", ActorLifecycleState::Running), "running");
        assert_eq!(format!("{}", ActorLifecycleState::Stopping), "stopping");
        assert_eq!(format!("{}", ActorLifecycleState::Stopped), "stopped");
        assert_eq!(format!("{}", ActorLifecycleState::Failed), "failed");
    }

    // --- Breakage Check: Invalid transitions return None ---
    #[test]
    fn given_pending_when_stop_then_none() {
        assert_eq!(
            compute_next_state(ActorLifecycleState::Pending, LifecycleTransition::Stop),
            None
        );
    }

    #[test]
    fn given_running_when_start_then_none() {
        assert_eq!(
            compute_next_state(ActorLifecycleState::Running, LifecycleTransition::Start),
            None
        );
    }

    #[test]
    fn given_stopping_when_fail_then_none() {
        assert_eq!(
            compute_next_state(ActorLifecycleState::Stopping, LifecycleTransition::Fail),
            None
        );
    }
}

// ============================================================================
// MODULE 2: FailureOutcome (ADR-042 Section 5)
// ============================================================================

mod bdd_failure_outcome {
    use super::*;
    use vo_types::signal::FailureScope;
    use vo_types::LineageStatus;

    // --- Claim: Epoch failure keeps lineage active ---
    #[test]
    fn given_running_when_epoch_failure_then_lineage_active() {
        let outcome = compute_failure_outcome(ActorLifecycleState::Running, FailureScope::Epoch);
        assert!(outcome.is_epoch_failure());
        assert!(!outcome.is_lineage_failure());
        assert_eq!(outcome.actor_state(), ActorLifecycleState::Failed);
        assert_eq!(outcome.lineage_status(), LineageStatus::Active);
        assert!(outcome.can_lineage_spawn_epoch());
    }

    // --- Claim: Lineage failure tombstones lineage ---
    #[test]
    fn given_running_when_lineage_failure_then_tombstoned() {
        let outcome = compute_failure_outcome(ActorLifecycleState::Running, FailureScope::Lineage);
        assert!(!outcome.is_epoch_failure());
        assert!(outcome.is_lineage_failure());
        assert_eq!(outcome.actor_state(), ActorLifecycleState::Failed);
        assert_eq!(outcome.lineage_status(), LineageStatus::Tombstoned);
        assert!(!outcome.can_lineage_spawn_epoch());
    }
}

// ============================================================================
// MODULE 3: ParentChildRegistry
// ============================================================================

mod bdd_parent_child_registry {
    use super::*;

    #[tokio::test]
    async fn given_empty_registry_when_add_child_then_child_exists() {
        let reg = ParentChildRegistry::new();
        let id = default_iid();
        reg.add_child(id.clone()).await;
        let children = reg.get_children().await;
        assert!(children.contains_key(&id));
        assert_eq!(children[&id].state, ActorLifecycleState::Pending);
    }

    #[tokio::test]
    async fn given_child_exists_when_remove_then_child_gone() {
        let reg = ParentChildRegistry::new();
        let id = default_iid();
        reg.add_child(id.clone()).await;
        reg.remove_child(&id).await;
        assert!(!reg.get_children().await.contains_key(&id));
    }

    #[tokio::test]
    async fn given_child_when_update_state_then_state_changed() {
        let reg = ParentChildRegistry::new();
        let id = default_iid();
        reg.add_child(id.clone()).await;
        let info = reg.update_child_state(&id, ActorLifecycleState::Running).await;
        assert_eq!(info.unwrap().state, ActorLifecycleState::Running);
    }

    #[tokio::test]
    async fn given_two_children_when_filter_by_state_then_correct_subset() {
        let reg = ParentChildRegistry::new();
        let id1 = iid("01H5JYV4XHGSR2F8KZ9BWNRFMA");
        let id2 = iid("01H5JYV4XHGSR2F8KZ9BWNRFMB");
        reg.add_child(id1.clone()).await;
        reg.add_child(id2.clone()).await;
        reg.update_child_state(&id1, ActorLifecycleState::Running).await;

        let running = reg.get_children_by_state(ActorLifecycleState::Running).await;
        assert_eq!(running, vec![id1]);
        let pending = reg.get_children_by_state(ActorLifecycleState::Pending).await;
        assert_eq!(pending, vec![id2]);
    }

    #[tokio::test]
    async fn given_mixed_states_when_all_terminal_then_true_only_if_all_terminal() {
        let reg = ParentChildRegistry::new();
        let id1 = iid("01H5JYV4XHGSR2F8KZ9BWNRFMA");
        let id2 = iid("01H5JYV4XHGSR2F8KZ9BWNRFMB");
        reg.add_child(id1.clone()).await;
        reg.add_child(id2.clone()).await;
        assert!(!reg.all_children_terminal().await);

        reg.update_child_state(&id1, ActorLifecycleState::Stopped).await;
        assert!(!reg.all_children_terminal().await);

        reg.update_child_state(&id2, ActorLifecycleState::Failed).await;
        assert!(reg.all_children_terminal().await);
    }

    #[tokio::test]
    async fn given_children_when_active_count_then_only_non_terminal() {
        let reg = ParentChildRegistry::new();
        let id1 = iid("01H5JYV4XHGSR2F8KZ9BWNRFMA");
        let id2 = iid("01H5JYV4XHGSR2F8KZ9BWNRFMB");
        reg.add_child(id1.clone()).await;
        reg.add_child(id2.clone()).await;
        assert_eq!(reg.active_children_count().await, 2);

        reg.update_child_state(&id1, ActorLifecycleState::Stopped).await;
        assert_eq!(reg.active_children_count().await, 1);

        reg.update_child_state(&id2, ActorLifecycleState::Failed).await;
        assert_eq!(reg.active_children_count().await, 0);
    }
}

// ============================================================================
// MODULE 4: ReservedPermitBudget
// ============================================================================

mod bdd_reserved_permit_budget {
    use super::*;

    #[test]
    fn given_budget_when_acquire_then_available_decreases() {
        let mut budget = ReservedPermitBudget::new(3);
        assert_eq!(budget.available(WorkloadClass::Recovery), 3);
        budget.try_acquire(WorkloadClass::Recovery).unwrap();
        assert_eq!(budget.available(WorkloadClass::Recovery), 2);
    }

    #[test]
    fn given_exhausted_budget_when_acquire_then_budget_exhaustion_error() {
        let mut budget = ReservedPermitBudget::new(1);
        budget.try_acquire(WorkloadClass::Recovery).unwrap();
        let err = budget.try_acquire(WorkloadClass::Recovery).unwrap_err();
        assert!(matches!(err, StartError::BudgetExhaustion { class: WorkloadClass::Recovery, .. }));
    }

    #[test]
    fn given_one_acquired_when_release_then_available_increases() {
        let mut budget = ReservedPermitBudget::new(2);
        budget.try_acquire(WorkloadClass::Recovery).unwrap();
        budget.release(WorkloadClass::Recovery);
        assert_eq!(budget.available(WorkloadClass::Recovery), 2);
    }

    // --- Breakage Check: release at zero is a no-op ---
    #[test]
    fn given_no_acquires_when_release_then_noop() {
        let mut budget = ReservedPermitBudget::new(5);
        budget.release(WorkloadClass::Recovery);
        assert_eq!(budget.available(WorkloadClass::Recovery), 5);
    }

    // --- Claim: Classes are independent ---
    #[test]
    fn given_exhausted_recovery_when_acquire_internal_then_succeeds() {
        let mut budget = ReservedPermitBudget::new(1);
        budget.try_acquire(WorkloadClass::Recovery).unwrap();
        assert!(budget.try_acquire(WorkloadClass::Recovery).is_err());
        assert!(budget.try_acquire(WorkloadClass::Internal).is_ok());
    }

    #[test]
    fn given_budget_when_reset_then_all_available() {
        let mut budget = ReservedPermitBudget::new(5);
        budget.try_acquire(WorkloadClass::Recovery).unwrap();
        budget.try_acquire(WorkloadClass::NewInstance).unwrap();
        budget.reset();
        assert_eq!(budget.available(WorkloadClass::Recovery), 5);
        assert_eq!(budget.available(WorkloadClass::NewInstance), 5);
    }

    #[test]
    fn given_new_budget_when_is_exhausted_then_false() {
        let budget = ReservedPermitBudget::new(5);
        assert!(!budget.is_exhausted(WorkloadClass::Recovery));
    }

    #[test]
    fn given_full_budget_when_is_exhausted_then_true() {
        let mut budget = ReservedPermitBudget::new(1);
        budget.try_acquire(WorkloadClass::Recovery).unwrap();
        assert!(budget.is_exhausted(WorkloadClass::Recovery));
    }
}

// ============================================================================
// MODULE 5: WorkloadClass (fairness.rs)
// ============================================================================

mod bdd_workload_class {
    use super::*;

    #[test]
    fn given_valid_string_when_parse_then_correct_variant() {
        assert_eq!("recovery".parse::<WorkloadClass>().unwrap(), WorkloadClass::Recovery);
        assert_eq!("new_instance".parse::<WorkloadClass>().unwrap(), WorkloadClass::NewInstance);
        assert_eq!("internal".parse::<WorkloadClass>().unwrap(), WorkloadClass::Internal);
    }

    #[test]
    fn given_case_insensitive_input_when_parse_then_succeeds() {
        assert_eq!("Recovery".parse::<WorkloadClass>().unwrap(), WorkloadClass::Recovery);
        assert_eq!("RECOVERY".parse::<WorkloadClass>().unwrap(), WorkloadClass::Recovery);
    }

    #[test]
    fn given_unknown_string_when_parse_then_error() {
        let result = "background".parse::<WorkloadClass>();
        assert!(result.is_err());
    }

    // --- Completeness Check: roundtrip display → parse ---
    #[test]
    fn given_any_class_when_display_then_parse_roundtrips() {
        for class in fairness::ALL_WORKLOAD_CLASSES {
            let s = class.to_string();
            let parsed: WorkloadClass = s.parse().unwrap();
            assert_eq!(class, parsed);
        }
    }

    // --- Claim: Default is Internal ---
    #[test]
    fn given_default_when_check_then_internal() {
        assert_eq!(WorkloadClass::default(), WorkloadClass::Internal);
    }
}

// ============================================================================
// MODULE 6: SignalBuffer
// ============================================================================

mod bdd_signal_buffer {
    use super::*;

    fn make_signal(id: &str) -> BufferedSignal {
        BufferedSignal::new(
            id.to_string(),
            SignalPayload::empty(),
            TimestampMs::now(),
        )
    }

    // --- Claim: Reject policy always rejects ---
    #[test]
    fn given_reject_policy_when_no_matching_wait_then_rejected() {
        let (delivery, result) = apply_policy(BufferPolicy::Reject, false, false);
        assert_eq!(delivery, SignalDelivery::Rejected);
        assert_eq!(result, Some(BufferResult::Rejected));
    }

    // --- Claim: BufferOne rejects second signal ---
    #[test]
    fn given_buffer_one_when_existing_buffer_then_rejected() {
        let (delivery, result) = apply_policy(BufferPolicy::BufferOne, false, true);
        assert_eq!(delivery, SignalDelivery::Rejected);
        assert_eq!(result, Some(BufferResult::Rejected));
    }

    // --- Claim: BufferOne accepts first signal ---
    #[test]
    fn given_buffer_one_when_no_existing_then_buffered() {
        let (delivery, result) = apply_policy(BufferPolicy::BufferOne, false, false);
        assert_eq!(delivery, SignalDelivery::Buffered);
        assert_eq!(result, Some(BufferResult::Buffered));
    }

    // --- Claim: Matching wait always accepts ---
    #[test]
    fn given_matching_wait_when_any_policy_then_accepted() {
        for policy in [BufferPolicy::Reject, BufferPolicy::BufferOne, BufferPolicy::BufferMany] {
            let (delivery, _) = apply_policy(policy, true, false);
            assert_eq!(delivery, SignalDelivery::Accepted);
        }
    }

    // --- Claim: BufferMany buffers multiple ---
    #[test]
    fn given_buffer_many_when_buffer_signal_then_multiple_stored() {
        let mut buf = SignalBuffer::new(SignalBufferConfig::new(5));
        let id = default_iid();
        let wk = WaitKey::parse("test-key").unwrap();

        assert_eq!(
            buf.buffer_signal(id.clone(), wk.clone(), make_signal("s1"), BufferPolicy::BufferMany),
            BufferResult::Buffered
        );
        assert_eq!(
            buf.buffer_signal(id.clone(), wk.clone(), make_signal("s2"), BufferPolicy::BufferMany),
            BufferResult::Buffered
        );
        assert_eq!(buf.buffered_count(&id, &wk), 2);
    }

    // --- Claim: BufferMany drops when full ---
    #[test]
    fn given_buffer_many_when_full_then_drops() {
        let mut buf = SignalBuffer::new(SignalBufferConfig::new(2));
        let id = default_iid();
        let wk = WaitKey::parse("test-key").unwrap();

        buf.buffer_signal(id.clone(), wk.clone(), make_signal("s1"), BufferPolicy::BufferMany);
        buf.buffer_signal(id.clone(), wk.clone(), make_signal("s2"), BufferPolicy::BufferMany);
        assert_eq!(
            buf.buffer_signal(id.clone(), wk.clone(), make_signal("s3"), BufferPolicy::BufferMany),
            BufferResult::Dropped
        );
    }

    // --- Claim: pop_buffered returns FIFO order ---
    #[test]
    fn given_buffered_when_pop_then_fifo_order() {
        let mut buf = SignalBuffer::new(SignalBufferConfig::new(10));
        let id = default_iid();
        let wk = WaitKey::parse("test-key").unwrap();

        buf.buffer_signal(id.clone(), wk.clone(), make_signal("first"), BufferPolicy::BufferMany);
        buf.buffer_signal(id.clone(), wk.clone(), make_signal("second"), BufferPolicy::BufferMany);

        let first = buf.pop_buffered(&id, &wk).unwrap();
        assert_eq!(first.signal_id, "first");
        let second = buf.pop_buffered(&id, &wk).unwrap();
        assert_eq!(second.signal_id, "second");
        assert!(buf.pop_buffered(&id, &wk).is_none());
    }

    // --- Claim: clear removes all signals for key ---
    #[test]
    fn given_buffered_when_clear_then_empty() {
        let mut buf = SignalBuffer::new(SignalBufferConfig::new(10));
        let id = default_iid();
        let wk = WaitKey::parse("test-key").unwrap();

        buf.buffer_signal(id.clone(), wk.clone(), make_signal("s1"), BufferPolicy::BufferMany);
        buf.clear(&id, &wk);
        assert_eq!(buf.buffered_count(&id, &wk), 0);
    }

    // --- Claim: total_buffered_count and num_keys_with_signals ---
    #[test]
    fn given_multiple_keys_when_count_then_correct_totals() {
        let mut buf = SignalBuffer::new(SignalBufferConfig::new(10));
        let id1 = iid("01H5JYV4XHGSR2F8KZ9BWNRFMA");
        let id2 = iid("01H5JYV4XHGSR2F8KZ9BWNRFMB");
        let wk = WaitKey::parse("key").unwrap();

        buf.buffer_signal(id1, wk.clone(), make_signal("s1"), BufferPolicy::BufferMany);
        buf.buffer_signal(id2, wk, make_signal("s2"), BufferPolicy::BufferMany);

        assert_eq!(buf.num_keys_with_signals(), 2);
        assert_eq!(buf.total_buffered_count(), 2);
    }

    // --- Claim: can_buffer rejects for Reject policy ---
    #[test]
    fn given_reject_policy_when_can_buffer_then_false() {
        let config = SignalBufferConfig::default();
        assert!(!can_buffer(BufferPolicy::Reject, false, 0, &config));
    }
}

// ============================================================================
// MODULE 7: WaitKey and SignalPayload validation
// ============================================================================

mod bdd_signal_messages_validation {
    use super::*;

    #[test]
    fn given_valid_string_when_waitkey_parse_then_ok() {
        let key = WaitKey::parse("approval-v2").unwrap();
        assert_eq!(key.as_str(), "approval-v2");
    }

    #[test]
    fn given_empty_string_when_waitkey_parse_then_err() {
        assert!(WaitKey::parse("").is_err());
    }

    #[test]
    fn given_over_256_when_waitkey_parse_then_err() {
        let long = "a".repeat(257);
        assert!(WaitKey::parse(&long).is_err());
    }

    #[test]
    fn given_256_chars_when_waitkey_parse_then_ok() {
        let exact = "a".repeat(256);
        assert!(WaitKey::parse(&exact).is_ok());
    }

    #[test]
    fn given_valid_bytes_when_signal_payload_then_ok() {
        let payload = SignalPayload::from_bytes(vec![1, 2, 3]).unwrap();
        assert_eq!(payload.as_bytes(), &[1, 2, 3]);
        assert_eq!(payload.len(), 3);
        assert!(!payload.is_empty());
    }

    #[test]
    fn given_over_64kib_when_signal_payload_then_err() {
        let big = vec![0u8; 65537];
        assert!(SignalPayload::from_bytes(big).is_err());
    }

    #[test]
    fn given_empty_payload_when_is_empty_then_true() {
        let payload = SignalPayload::empty();
        assert!(payload.is_empty());
        assert_eq!(payload.len(), 0);
    }
}

// ============================================================================
// MODULE 8: ControlActor Cancel/Resume/AcceptResume (lib.rs)
// ============================================================================

mod bdd_control_actor {
    use super::*;

    // --- Cancel success path ---
    #[test]
    fn given_running_instance_when_cancel_then_events_emitted() {
        let actor = ControlActor::new();
        let id = iid("01H5JYV4XHGSR2F8KZ9BWNRFMA");
        let (cancel_req, workflow_cancelled) = actor.handle_cancel(id.clone()).unwrap();
        assert_eq!(cancel_req.instance_id, id);
        assert_eq!(workflow_cancelled.instance_id, id);
        assert!(workflow_cancelled.cancelled_at >= cancel_req.requested_at);
    }

    // --- Cancel on terminal: AlreadyTerminal ---
    #[test]
    fn given_completed_instance_when_cancel_then_already_terminal() {
        let actor = ControlActor::new();
        let id = iid("01H5JYV4XHGSR2F8KZ9B00C000"); // Completed
        match actor.handle_cancel(id.clone()) {
            Err(CancelError::AlreadyTerminal { current_state: LifecycleState::Completed, .. }) => {}
            other => panic!("Expected AlreadyTerminal(Completed), got {:?}", other),
        }
    }

    // --- Cancel on cancelled: AlreadyTerminal ---
    #[test]
    fn given_cancelled_instance_when_cancel_then_already_terminal() {
        let actor = ControlActor::new();
        let id = iid("01H5JYV4XHGSR2F8KZ9B00X000"); // Cancelled
        match actor.handle_cancel(id.clone()) {
            Err(CancelError::AlreadyTerminal { current_state: LifecycleState::Cancelled, .. }) => {}
            other => panic!("Expected AlreadyTerminal(Cancelled), got {:?}", other),
        }
    }

    // --- Cancel non-existent: InstanceActorNotFound ---
    #[test]
    fn given_nonexistent_instance_when_cancel_then_not_found() {
        let actor = ControlActor::new();
        let id = iid("00000000000000000000000001");
        match actor.handle_cancel(id) {
            Err(CancelError::InstanceActorNotFound { .. }) => {}
            other => panic!("Expected InstanceActorNotFound, got {:?}", other),
        }
    }

    // --- Cancel lock failure ---
    #[test]
    fn given_lock_error_when_cancel_then_lock_failed() {
        let actor = ControlActor::new();
        let id = iid("01H5JYV4XHGSR2F8KZ9BA00000"); // 'A' = lock error
        match actor.handle_cancel(id) {
            Err(CancelError::LockAcquisitionFailed { .. }) => {}
            other => panic!("Expected LockAcquisitionFailed, got {:?}", other),
        }
    }

    // --- Cancel storage failure ---
    #[test]
    fn given_storage_error_when_cancel_then_storage_error() {
        let actor = ControlActor::new();
        let id = iid("01H5JYV4XHGSR2F8KZ9BS00000"); // 'S' = storage error
        match actor.handle_cancel(id) {
            Err(CancelError::StorageError { .. }) => {}
            other => panic!("Expected StorageError, got {:?}", other),
        }
    }

    // --- Resume success path ---
    #[test]
    fn given_failed_instance_when_resume_then_instance_resumed() {
        let actor = ControlActor::new();
        let id = iid("01H5JYV4XHGSR2F8KZ9B00F000"); // Failed
        let resumed = actor.handle_resume(id.clone()).unwrap();
        assert_eq!(resumed.instance_id, id);
        assert_ne!(resumed.previous_binary_hash, resumed.resumed_binary_hash);
    }

    // --- Resume non-failed: InvalidLifecycleState ---
    #[test]
    fn given_running_instance_when_resume_then_invalid_state() {
        let actor = ControlActor::new();
        let id = iid("01H5JYV4XHGSR2F8KZ9B000000"); // Running
        match actor.handle_resume(id) {
            Err(ResumeError::InvalidLifecycleState { actual: LifecycleState::Running, expected: LifecycleState::Failed }) => {}
            other => panic!("Expected InvalidLifecycleState, got {:?}", other),
        }
    }

    // --- Resume error taxonomy: all precondition errors ---
    #[test]
    fn given_resume_errors_when_classify_then_preconditions_correct() {
        let id = default_iid();
        let precondition: Vec<ResumeError> = vec![
            ResumeError::InvalidLifecycleState { actual: LifecycleState::Running, expected: LifecycleState::Failed },
            ResumeError::MissingSecrets { instance_id: id.clone(), missing_secret_ids: vec![SecretId::new("s1")] },
            ResumeError::NodeNotFound { instance_id: id.clone(), node_name: NodeName::new("n1") },
            ResumeError::NoPathToTerminal { instance_id: id.clone(), current_node: NodeName::new("n2") },
            ResumeError::InstanceActorNotFound { instance_id: id.clone() },
        ];
        for err in &precondition {
            assert!(err.is_precondition(), "Expected {:?} to be precondition", err);
            assert!(!err.is_transient(), "Expected {:?} to NOT be transient", err);
        }

        let transient: Vec<ResumeError> = vec![
            ResumeError::LockAcquisitionFailed { instance_id: id.clone(), reason: "locked".to_string() },
            ResumeError::StorageError { instance_id: id, reason: "io".to_string() },
        ];
        for err in &transient {
            assert!(!err.is_precondition(), "Expected {:?} to NOT be precondition", err);
            assert!(err.is_transient(), "Expected {:?} to be transient", err);
        }
    }

    // --- AcceptResume success ---
    #[test]
    fn given_waiting_for_signal_when_accept_and_resume_then_outcome() {
        let actor = ControlActor::new();
        let id = iid("01H5JYV4XHGSR2F8KZ9B00W000"); // WaitingForSignal
        let wk = WaitKey::parse("approval").unwrap();
        let outcome = actor.accept_and_resume(id.clone(), wk, "sig-1".to_string(), SignalPayload::empty()).unwrap();
        assert_eq!(outcome.accepted.instance_id, id);
        assert_eq!(outcome.resumed.instance_id, id);
    }

    // --- AcceptResume error classification ---
    #[test]
    fn given_accept_resume_errors_when_classify_then_correct() {
        let id = default_iid();
        let precondition: Vec<AcceptResumeError> = vec![
            AcceptResumeError::InvalidLifecycleState { instance_id: id.clone(), actual: LifecycleState::Running, expected: LifecycleState::WaitingForSignal },
            AcceptResumeError::WaitKeyMismatch { instance_id: id.clone(), expected_key: WaitKey::new_unchecked("a"), provided_key: WaitKey::new_unchecked("b") },
            AcceptResumeError::InstanceActorNotFound { instance_id: id.clone() },
            AcceptResumeError::PayloadTooLarge { instance_id: id, payload_size: 65537, max_size: 65536 },
        ];
        for err in &precondition {
            assert!(err.is_precondition());
            assert!(!err.is_transient());
        }
    }
}

// ============================================================================
// MODULE 9: InstanceRegistry (single-active guarantee)
// ============================================================================

mod bdd_instance_registry {
    use super::*;

    #[test]
    fn given_empty_registry_when_register_then_active() {
        let mut reg = InstanceRegistry::new(RegistryConfig::default());
        let id = default_iid();
        reg.register(id.clone(), InstanceActorHandle::test(1), |_h| Ok(())).unwrap();
        assert!(reg.is_active(&id));
        assert_eq!(reg.active_count(), 1);
    }

    #[test]
    fn given_active_when_register_same_id_then_stop_before_replace() {
        let mut reg = InstanceRegistry::new(RegistryConfig::default());
        let id = default_iid();
        reg.register(id.clone(), InstanceActorHandle::test(1), |_h| Ok(())).unwrap();

        // Re-register with new handle — prior should be stopped
        reg.register(id.clone(), InstanceActorHandle::test(2), |_h| Ok(())).unwrap();
        assert!(reg.is_active(&id));
        let handle = reg.lookup(&id).unwrap();
        assert_eq!(handle.handle_id(), 2); // New handle replaced old
    }

    #[test]
    fn given_active_when_register_and_stop_fails_then_old_preserved() {
        let mut reg = InstanceRegistry::new(RegistryConfig::default());
        let id = default_iid();
        reg.register(id.clone(), InstanceActorHandle::test(1), |_h| Ok(())).unwrap();

        // Try to re-register but stop_fn fails
        let result = reg.register(id.clone(), InstanceActorHandle::test(2), |_h| Err("stop failed".to_string()));
        assert!(result.is_err());
        // INV-5: Old handle preserved
        let handle = reg.lookup(&id).unwrap();
        assert_eq!(handle.handle_id(), 1);
    }

    #[test]
    fn given_active_when_deregister_then_removed() {
        let mut reg = InstanceRegistry::new(RegistryConfig::default());
        let id = default_iid();
        reg.register(id.clone(), InstanceActorHandle::test(1), |_h| Ok(())).unwrap();
        let handle = reg.deregister(&id).unwrap();
        assert_eq!(handle.handle_id(), 1);
        assert!(!reg.is_active(&id));
    }

    #[test]
    fn given_not_registered_when_deregister_then_not_registered_error() {
        let mut reg = InstanceRegistry::new(RegistryConfig::default());
        let id = default_iid();
        let result = reg.deregister(&id);
        assert!(matches!(result, Err(RegistryError::NotRegistered { .. })));
    }

    // --- INV-3: Count consistency ---
    #[test]
    fn given_multiple_registrations_when_count_then_consistent() {
        let mut reg = InstanceRegistry::new(RegistryConfig::default());
        let id1 = iid("01H5JYV4XHGSR2F8KZ9BWNRFMA");
        let id2 = iid("01H5JYV4XHGSR2F8KZ9BWNRFMB");

        reg.register(id1, InstanceActorHandle::test(1), |_h| Ok(())).unwrap();
        reg.register(id2, InstanceActorHandle::test(2), |_h| Ok(())).unwrap();
        assert_eq!(reg.active_count(), 2);

        reg.deregister(&iid("01H5JYV4XHGSR2F8KZ9BWNRFMA")).unwrap();
        assert_eq!(reg.active_count(), 1);
    }
}

// ============================================================================
// MODULE 10: SpawnSupervisor pure calculations
// ============================================================================

mod bdd_spawn_supervisor_calc {
    use super::*;

    #[test]
    fn given_first_attempt_when_backoff_then_initial() {
        assert_eq!(calculate_backoff_delay(1000, 2.0, 1), 1000);
    }

    #[test]
    fn given_later_attempt_when_backoff_then_exponential() {
        assert_eq!(calculate_backoff_delay(1000, 2.0, 2), 2000);
        assert_eq!(calculate_backoff_delay(1000, 2.0, 3), 4000);
    }

    #[test]
    fn given_multiplier_1_when_backoff_then_constant() {
        assert_eq!(calculate_backoff_delay(1000, 1.0, 1), 1000);
        assert_eq!(calculate_backoff_delay(1000, 1.0, 10), 1000);
    }

    #[test]
    fn given_failed_high_attempts_when_is_zombie_then_true() {
        let record = SpawnRecord {
            spawn_id: None,
            instance_id: default_iid(),
            command: "test".to_string(),
            spawn_phase: SpawnPhase::Failed,
            health_checks: 0,
            spawn_attempts: 5,
            last_error: None,
        };
        assert!(is_zombie_state(&record));
    }

    #[test]
    fn given_failed_low_attempts_when_is_zombie_then_false() {
        let record = SpawnRecord {
            spawn_id: None,
            instance_id: default_iid(),
            command: "test".to_string(),
            spawn_phase: SpawnPhase::Failed,
            health_checks: 0,
            spawn_attempts: 2,
            last_error: None,
        };
        assert!(!is_zombie_state(&record));
    }

    #[test]
    fn given_failed_within_limit_when_should_respawn_then_true() {
        let record = SpawnRecord {
            spawn_id: None,
            instance_id: default_iid(),
            command: "test".to_string(),
            spawn_phase: SpawnPhase::Failed,
            health_checks: 0,
            spawn_attempts: 2,
            last_error: None,
        };
        assert!(should_respawn(&record, 5));
    }

    #[test]
    fn given_failed_at_limit_when_should_respawn_then_false() {
        let record = SpawnRecord {
            spawn_id: None,
            instance_id: default_iid(),
            command: "test".to_string(),
            spawn_phase: SpawnPhase::Failed,
            health_checks: 0,
            spawn_attempts: 5,
            last_error: None,
        };
        assert!(!should_respawn(&record, 5));
    }

    // --- Claim: SpawnRecord transitions are pure (return new, don't mutate) ---
    #[test]
    fn given_record_when_transition_then_original_unchanged() {
        let original = SpawnRecord::new(default_iid(), "cmd".to_string(), None);
        let _health = original.transition_to_health_check();
        assert_eq!(original.spawn_phase, SpawnPhase::Spawn); // original unchanged
    }

    // --- Claim: respawn increments attempts ---
    #[test]
    fn given_record_when_respawn_then_attempts_incremented() {
        let record = SpawnRecord {
            spawn_id: None,
            instance_id: default_iid(),
            command: "test".to_string(),
            spawn_phase: SpawnPhase::Failed,
            health_checks: 0,
            spawn_attempts: 3,
            last_error: None,
        };
        let respawned = record.respawn(None);
        assert_eq!(respawned.spawn_attempts, 4);
        assert_eq!(respawned.spawn_phase, SpawnPhase::Spawn);
        assert_eq!(respawned.health_checks, 0);
    }

    // --- Error taxonomy claims ---
    #[test]
    fn given_errors_when_classify_then_correct_categories() {
        let transient = SpawnSupervisorError::StorageError("x".to_string());
        let resumable = SpawnSupervisorError::HealthCheckFailed {
            instance_id: default_iid(),
            check_number: 1,
            error: "fail".to_string(),
        };
        let fatal = SpawnSupervisorError::CorruptSpawn("bad".to_string());
        let operational = SpawnSupervisorError::AlreadyRunning;

        assert!(transient.is_transient());
        assert!(!transient.is_resumable());
        assert!(resumable.is_resumable());
        assert!(!resumable.is_fatal());
        assert!(fatal.is_fatal());
        assert!(!fatal.is_operational());
        assert!(operational.is_operational());
    }
}

// ============================================================================
// MODULE 11: Timer primitives
// ============================================================================

mod bdd_timers {
    use super::*;

    #[test]
    fn given_valid_input_when_timer_wait_key_then_ok() {
        let key = TimerWaitKey::parse("my-timer").unwrap();
        assert_eq!(key.as_str(), "my-timer");
    }

    #[test]
    fn given_empty_when_timer_wait_key_then_err() {
        assert!(TimerWaitKey::parse("").is_err());
    }

    #[test]
    fn given_too_long_when_timer_wait_key_then_err() {
        assert!(TimerWaitKey::parse(&"x".repeat(257)).is_err());
    }

    #[test]
    fn given_valid_params_when_compute_fire_at_then_correct() {
        assert_eq!(compute_fire_at(1000, 500).unwrap(), 1500);
    }

    #[test]
    fn given_overflow_when_compute_fire_at_then_err() {
        assert!(compute_fire_at(u64::MAX, 1).is_err());
    }

    #[test]
    fn given_positive_when_validate_sleep_duration_then_ok() {
        assert_eq!(validate_sleep_duration(100).unwrap(), 100);
    }

    #[test]
    fn given_zero_or_negative_when_validate_sleep_then_err() {
        assert!(validate_sleep_duration(0).is_err());
        assert!(validate_sleep_duration(-1).is_err());
    }

    #[test]
    fn given_valid_sleep_state_when_remaining_then_correct() {
        let state = SleepState::new(
            default_iid(),
            TimerWaitKey::parse("t").unwrap(),
            5000,
            1000,
        ).unwrap();
        assert_eq!(state.remaining_ms(3000), 2000);
        assert_eq!(state.remaining_ms(5000), 0);
        assert_eq!(state.remaining_ms(6000), 0); // saturating
    }

    #[test]
    fn given_fire_at_equals_now_when_is_expired_then_true() {
        assert!(is_timer_expired(1000, 1000));
        assert!(!is_timer_expired(1001, 1000));
    }
}

// ============================================================================
// MODULE 12: Reanimator types
// ============================================================================

mod bdd_reanimator_types {
    use super::*;

    #[test]
    fn given_timers_when_filter_by_fairness_then_budget_respected() {
        let id1 = iid("01H5JYV4XHGSR2F8KZ9BWNRFMA");
        let id2 = iid("01H5JYV4XHGSR2F8KZ9BWNRFMB");
        let timers = vec![
            TimerRecord::new(id1.clone(), TimestampMs::now(), None, TimestampMs::now()),
            TimerRecord::new(id1.clone(), TimestampMs::now(), None, TimestampMs::now()),
            TimerRecord::new(id2.clone(), TimestampMs::now(), None, TimestampMs::now()),
        ];
        let mut budget = FairnessBudget::with_limits(1, 10);
        let (allowed, rejected) = filter_timers_by_fairness(timers, &budget);
        assert_eq!(allowed.len(), 2); // id1 first timer + id2
        assert_eq!(rejected.len(), 1); // id1 second timer

        // Record the allowed ones
        for t in &allowed {
            assert!(budget.record_resume(t.instance_id.clone()));
        }
    }

    #[test]
    fn given_remaining_when_calculate_batch_then_min_of_remaining_and_budget() {
        assert_eq!(calculate_batch_size(100, 50, 0), 50);
        assert_eq!(calculate_batch_size(30, 50, 0), 30);
        assert_eq!(calculate_batch_size(100, 50, 40), 10);
    }

    #[test]
    fn given_valid_record_when_validate_then_ok() {
        let record = TimerRecord::new(default_iid(), TimestampMs::new_unchecked(5000), None, TimestampMs::new_unchecked(1000));
        assert!(validate_timer_record(&record).is_ok());
    }

    #[test]
    fn given_zero_fire_at_when_validate_then_err() {
        let record = TimerRecord::new(default_iid(), TimestampMs::new_unchecked(0), None, TimestampMs::new_unchecked(1000));
        assert!(validate_timer_record(&record).is_err());
    }

    #[test]
    fn given_fire_before_scheduled_when_validate_then_err() {
        let record = TimerRecord::new(default_iid(), TimestampMs::new_unchecked(500), None, TimestampMs::new_unchecked(1000));
        assert!(validate_timer_record(&record).is_err());
    }

    #[test]
    fn given_reanimator_state_when_is_active_then_correct() {
        assert!(!ReanimatorState::Stopped.is_active());
        assert!(ReanimatorState::Running.is_active());
        assert!(ReanimatorState::ShuttingDown.is_active());
        assert!(!ReanimatorState::ShutDown.is_active());
    }

    #[test]
    fn given_fairness_budget_when_record_resume_then_increments() {
        let mut budget = FairnessBudget::with_limits(2, 10);
        let id = default_iid();
        assert!(budget.record_resume(id.clone()));
        assert!(budget.record_resume(id.clone()));
        assert!(!budget.record_resume(id.clone())); // exceeded
    }

    #[test]
    fn given_fairness_budget_when_reset_then_all_allowed() {
        let mut budget = FairnessBudget::with_limits(1, 10);
        let id = default_iid();
        budget.record_resume(id.clone());
        budget.reset();
        assert!(budget.can_resume(&id));
    }
}

// ============================================================================
// MODULE 13: MessageRouter
// ============================================================================

mod bdd_message_router {
    use super::*;

    #[test]
    fn given_empty_router_when_register_channel_then_has_channel() {
        let mut router = MessageRouter::with_default_config();
        let ch = ChannelId::new("test");
        router.register_channel(ch.clone(), ActorDestination::new("actor")).unwrap();
        assert!(router.has_channel(&ch));
        assert_eq!(router.num_channels(), 1);
    }

    #[test]
    fn given_existing_channel_when_register_same_then_error() {
        let mut router = MessageRouter::with_default_config();
        let ch = ChannelId::new("test");
        router.register_channel(ch.clone(), ActorDestination::new("a1")).unwrap();
        let result = router.register_channel(ch.clone(), ActorDestination::new("a2"));
        assert!(matches!(result, Err(RouteError::ChannelAlreadyExists(_))));
    }

    #[test]
    fn given_channel_when_unregister_then_removed() {
        let mut router = MessageRouter::with_default_config();
        let ch = ChannelId::new("test");
        router.register_channel(ch.clone(), ActorDestination::new("a1")).unwrap();
        router.unregister_channel(&ch);
        assert!(!router.has_channel(&ch));
    }

    #[test]
    fn given_channel_when_deactivate_then_no_active_destinations() {
        let mut router = MessageRouter::with_default_config();
        let ch = ChannelId::new("test");
        router.register_channel(ch.clone(), ActorDestination::new("a1")).unwrap();
        router.deactivate_channel(&ch).unwrap();
        assert!(!router.is_channel_active(&ch));
    }

    #[test]
    fn given_full_dlq_when_enqueue_then_fifo_eviction() {
        let mut dlq = DeadLetterQueue::new(2);
        for i in 0..4 {
            dlq.enqueue(DeadLetterEntry {
                channel_id: ChannelId::new(format!("ch-{}", i)),
                message: DeadLetterMessage { payload: vec![], type_name: "test".to_string() },
                enqueued_at: TimestampMs::now(),
                reason: DeadLetterReason::ChannelNotFound,
            });
        }
        assert_eq!(dlq.len(), 2);
        let ids: Vec<&str> = dlq.entries.iter().map(|e| e.channel_id.as_str()).collect();
        assert!(ids.contains(&"ch-2"));
        assert!(ids.contains(&"ch-3"));
        assert!(!ids.contains(&"ch-0"));
    }

    // --- ChannelId validation ---
    #[test]
    fn given_empty_string_when_channel_id_parse_then_err() {
        assert!(ChannelId::parse("").is_err());
    }

    #[test]
    fn given_non_empty_when_channel_id_then_ok() {
        let id = ChannelId::new("my-channel");
        assert_eq!(id.as_str(), "my-channel");
    }
}

// ============================================================================
// MODULE 14: Semaphore types
// ============================================================================

mod bdd_semaphore_types {
    use super::*;

    #[test]
    fn given_default_config_when_check_then_sensible_values() {
        let config = SemaphoreConfig::default();
        assert_eq!(config.max_concurrent_binaries, 500);
        assert_eq!(config.max_waiters_for_shed, 5000);
        assert_eq!(config.max_per_workflow, 10);
        assert_eq!(config.reserved_permits, 50);
    }

    #[test]
    fn given_backpressure_when_ordering_then_healthy_lt_shed() {
        assert!(BackpressureStatus::Healthy < BackpressureStatus::ShedLoad);
        assert!(BackpressureStatus::Moderate < BackpressureStatus::Heavy);
    }

    #[test]
    fn given_shed_load_when_should_reject_then_true() {
        assert!(BackpressureStatus::ShedLoad.should_reject());
        assert!(!BackpressureStatus::Heavy.should_reject());
    }

    #[test]
    fn given_heavy_or_shed_when_is_queued_then_true() {
        assert!(BackpressureStatus::Heavy.is_queued());
        assert!(BackpressureStatus::ShedLoad.is_queued());
        assert!(!BackpressureStatus::Healthy.is_queued());
        assert!(!BackpressureStatus::Moderate.is_queued());
    }
}

// ============================================================================
// MODULE 15: ShutdownPropagator
// ============================================================================

mod bdd_shutdown_propagator {
    use super::*;

    #[test]
    fn given_default_propagator_when_check_timeouts_then_30s_10s() {
        let p = ShutdownPropagator::default_propagator();
        assert_eq!(p.graceful_timeout(), Duration::from_secs(30));
        assert_eq!(p.force_kill_timeout(), Duration::from_secs(10));
    }

    #[test]
    fn given_custom_timeouts_when_create_then_stored() {
        let p = ShutdownPropagator::new(Duration::from_secs(60), Duration::from_secs(20));
        assert_eq!(p.graceful_timeout(), Duration::from_secs(60));
        assert_eq!(p.force_kill_timeout(), Duration::from_secs(20));
    }
}

// ============================================================================
// MODULE 16: RolloverState and WorkflowContinued (epoch rollover)
// ============================================================================

mod bdd_rollover {
    use super::*;

    #[test]
    fn given_empty_rollover_when_create_then_no_keys() {
        let state = RolloverState::empty();
        assert!(state.dedupe_keys.is_empty());
        assert!(state.pending_wait_keys.is_empty());
    }

    #[test]
    fn given_rollover_with_keys_when_continue_then_keys_carried() {
        let rollover = RolloverState {
            dedupe_keys: vec!["cmd-1".to_string()],
            pending_wait_keys: vec!["approval".to_string()],
        };
        let continued = WorkflowContinued {
            old_instance_id: default_iid(),
            new_instance_id: iid("01H5JYV4XHGSR2F8KZ9BWNRFMB"),
            lineage_id: "lineage-abc".to_string(),
            old_epoch: 0,
            new_epoch: 1,
            continued_at: TimestampMs::now(),
            carried_dedupe_keys: rollover.dedupe_keys.clone(),
            carried_wait_keys: rollover.pending_wait_keys.clone(),
        };
        assert_eq!(continued.carried_dedupe_keys, vec!["cmd-1"]);
        assert_eq!(continued.carried_wait_keys, vec!["approval"]);
    }
}

// ============================================================================
// MODULE 17: Error display messages
// ============================================================================

mod bdd_error_display {
    use super::*;

    #[test]
    fn given_lifecycle_error_when_display_then_human_readable() {
        let err = LifecycleError::InvalidTransition {
            from: ActorLifecycleState::Running,
            attempted: LifecycleTransition::Start,
        };
        assert!(format!("{}", err).contains("invalid transition"));

        let err = LifecycleError::ChildNotFound(default_iid());
        assert!(format!("{}", err).contains("child not found"));

        let err = LifecycleError::CannotSpawnChild(ActorLifecycleState::Stopped);
        assert!(format!("{}", err).contains("cannot spawn child"));

        let err = LifecycleError::ShutdownTimeout { children_remaining: 3 };
        assert!(format!("{}", err).contains("shutdown timeout"));
    }

    #[test]
    fn given_start_error_when_display_then_contains_class() {
        let err = StartError::BudgetExhaustion {
            class: WorkloadClass::Recovery,
            requested: 1,
            available: 0,
        };
        let msg = format!("{}", err);
        assert!(msg.contains("Recovery"));
        assert!(msg.contains("requested"));
        assert!(msg.contains("available"));
    }

    #[test]
    fn given_registry_error_when_display_then_contextual() {
        let err = RegistryError::StopFailed {
            instance_id: default_iid(),
            reason: "timeout".to_string(),
        };
        assert!(format!("{}", err).contains("stop failed"));

        let err = RegistryError::StopTimeout {
            instance_id: default_iid(),
            timeout: Duration::from_secs(5),
        };
        assert!(format!("{}", err).contains("stop timeout"));

        let err = RegistryError::NotRegistered { instance_id: default_iid() };
        assert!(format!("{}", err).contains("not registered"));
    }
}
