[package]
name = "vo-types"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
proptest = ["dep:proptest"]

[dependencies]
thiserror.workspace = true
serde.workspace = true
ulid = { workspace = true, features = ["serde"] }
uuid.workspace = true
serde_json.workspace = true
proptest = { version = "1", optional = true }
spqr-tree = { workspace = true }
any-rope = { workspace = true }

[dev-dependencies]
rstest.workspace = true
serde_json.workspace = true
proptest = { version = "1", features = ["fork"] }
tokio = { workspace = true, features = ["full"] }
criterion = { workspace = true }

[[bench]]
name = "types_bench"
harness = false

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }
