[package]
name = "vo-storage"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
proptest = []

[dependencies]
fjall = { workspace = true }
memmap2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
vo-types = { workspace = true }
parking_lot = { workspace = true }
crc32fast = { workspace = true }
sha2 = { workspace = true }
blake3 = { workspace = true }
tokio = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
aes = "0.7"
aes-gcm = "0.9"
rand = "0.8"
ulid = { workspace = true }
generic-array = "0.14"

[dev-dependencies]
proptest = { workspace = true }
tempfile = { workspace = true }
rstest = { workspace = true }
