[package]
name = "vo-storage"
version = "0.1.0"
edition = "2021"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)', 'cfg(feature, values("proptest"))'] }

[features]
proptest = []

[dependencies]
fjall = { workspace = true }
memmap2 = "0.9"
serde = { workspace = true }
serde_json = { workspace = true }
vo-types = { workspace = true }
parking_lot = "0.12"
crc32fast = { workspace = true }
sha2 = { workspace = true }
blake3 = { workspace = true }
tokio = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
aes = "0.7"
aes-gcm = "0.9"
rand = "0.8"
generic-array = "0.14"

[dev-dependencies]
proptest = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
rstest = { workspace = true }
ulid = { workspace = true }
