[package]
name = "vo-linter"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
syn = { version = "2", features = ["full", "visit", "extra-traits"] }
thiserror = "2"

[dev-dependencies]
quote = "1"
criterion = { workspace = true }

[[bench]]
name = "linter_bench"
harness = false
[lints]
workspace = true
