[package]
name = "vo-sdk"
version.workspace = true
edition.workspace = true

[dependencies]
vo-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
proptest = { workspace = true }
tempfile = { workspace = true }
criterion = { workspace = true }
insta = { workspace = true }
