[package]
name = "vo-common"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait = "0.1"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true, optional = true }
ulid = { workspace = true, features = ["serde"] }
vo-types = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[features]
default = []
telemetry = ["dep:tracing"]

[lints]
workspace = true
