[package]
name = "vo-common"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true, optional = true }
ulid = { workspace = true, features = ["serde"] }

[dev-dependencies]
proptest = { workspace = true }
criterion = { workspace = true }
rand = { workspace = true }

[[bench]]
name = "octree_bench"
harness = false

[features]
default = []
telemetry = ["dep:tracing"]

[lints]
workspace = true
