[package]
name = "vo-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vo-common = { path = "../vo-common" }
vo-storage = { path = "../vo-storage" }
vo-types = { path = "../vo-types" }

# Async
tokio = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }

# NATS
async-nats = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
bytes = { workspace = true }
rmp-serde = { workspace = true }

# Utilities
thiserror = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }

# Actor framework
ractor = { workspace = true }

# ID generation
ulid = { workspace = true }

# HTTP
reqwest = { workspace = true }

# CRC
crc32fast = "1.4"

[dev-dependencies]
anyhow = { workspace = true }
proptest = { version = "1", features = ["fork"] }

[lib]
path = "src/lib.rs"
