[package]
name = "vo-actor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vo-types = { workspace = true }
ractor.workspace = true
thiserror = "1"
async-trait = "0.1"
tracing = "0.1"
tokio = { workspace = true, features = ["rt", "sync", "time", "macros"] }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ulid = "1"

[dev-dependencies]
proptest.workspace = true
ulid = "1"
criterion = { workspace = true }

[[bench]]
name = "reanimator_bench"
harness = false
