[package]
name = "vo-actor"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
proptest = ["dep:proptest"]

[dependencies]
vo-types = { workspace = true }
bytes = { workspace = true }
ractor.workspace = true
thiserror.workspace = true
async-trait = "0.1"
tracing = "0.1"
tokio = { workspace = true, features = ["rt", "sync", "time", "macros"] }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ulid = { workspace = true }
reqwest = { workspace = true }
proptest = { workspace = true, optional = true }

[dev-dependencies]
vo-core = { path = "../vo-core" }
proptest.workspace = true
criterion = { workspace = true }

[[bench]]
name = "reanimator_bench"
harness = false

[lints]
workspace = true
