[package]
name = "vo-executor"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
serde = { version = "1", features = ["derive"] }
tokio = { workspace = true, features = ["time", "sync"] }
dashmap = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros", "time", "sync"] }
proptest = { workspace = true }
serde_json = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "executor_bench"
harness = false
