#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::cast_precision_loss,
    clippy::cast_lossless,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::fn_to_numeric_cast,
    clippy::fn_to_numeric_cast_any,
    clippy::must_use_candidate,
    clippy::missing_errors_doc,
    clippy::missing_panics_doc,
    clippy::doc_markdown,
    clippy::redundant_closure,
    clippy::map_unwrap_or,
    clippy::duration_suboptimal_units,
    clippy::manual_midpoint,
    clippy::uninlined_format_args,
    clippy::needless_pass_by_value,
    clippy::implicit_hasher,
    clippy::significant_drop_tightening,
    clippy::match_same_arms,
    clippy::unnecessary_trailing_comma,
    clippy::unnested_or_patterns,
    clippy::bool_comparison,
    clippy::collapsible_if,
    clippy::too_many_lines,
    clippy::iter_with_drain,
    clippy::manual_map,
    clippy::bool_to_int_with_if,
    clippy::collapsible_else_if,
    clippy::comparison_chain,
    clippy::explicit_iter_loop,
    clippy::format_push_string,
    clippy::if_not_else,
    clippy::items_after_statements,
    clippy::manual_assert,
    clippy::redundant_closure_for_method_calls,
    clippy::ref_option,
    clippy::return_self_not_must_use,
    clippy::struct_field_names,
    clippy::type_complexity,
    clippy::unnecessary_map_or,
    clippy::unnecessary_wraps,
    clippy::unreadable_literal,
    clippy::unused_self,
    clippy::option_if_let_else,
    clippy::manual_let_else,
    clippy::semicolon_if_nothing_returned,
    dead_code
)]

pub mod error;
pub mod job;
pub mod queue;
pub mod types;

#[cfg(test)]
mod queue_tests;
