[package]
name = "vo-scheduler"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vo-common = { path = "../vo-common" }
vo-types = { path = "../vo-types" }
thiserror.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
ulid = { workspace = true, features = ["serde"] }
chrono = { workspace = true, features = ["serde"] }
bytes = { workspace = true, features = ["serde"] }
fjall = { workspace = true }
rmp-serde = { workspace = true }

[dev-dependencies]
rstest.workspace = true
proptest = { version = "1", features = ["fork"] }
tokio = { workspace = true, features = ["full"] }
tempfile = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }
