[package]
name = "vo-scheduler"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
ulid = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true